spring:
  application:
    name: capture-this

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: capturethis
    hibernate:
      ddl-auto: create
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d00ifhidbo4c7393er6g-a:5432/capturethis_db
    username: capturethis_db_user
    password: aFtpyGiXukm14LLk354aL7rLhMgyYLKy

  mvc:
    hidden-method:
      filter:
        enabled: true

  messages:
    basename: "messages,config.i18n.messages"
    fallback-to-system-locale: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

server:
  port: 8080
